server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          api1:
            client-id: plain_user
            client-secret: clientSecret
            authorization-grant-type: client_credentials
            scope: openid
          api2:
            client-id: privileged_user
            client-secret: clientSecret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          api1:
            issuer-uri: https://b48b-31-222-83-252.ngrok.io/cas/oidc
          api2:
            issuer-uri: https://b48b-31-222-83-252.ngrok.io/cas/oidc
      resourceserver:
        jwt:
          jws-algorithm: RS512
          jwk-set-uri: http://entrada:8080/cas/oidc/jwks
