server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    configUrl: /swagger-ui/swagger-config.json
    #oauth2RedirectUrl: http://apidocs.umes/swagger-ui/oauth2-redirect.html
    #oauth2-redirect-url: http://apidocs.umes/swagger-ui/oauth2-redirect.html
    display-request-duration: true
    oauth:      
      usePkceWithAuthorizationCodeGrant: true
      clientId: clientid

oauth:
  issuer-uri: https://3c03-31-222-83-252.ngrok.io/cas/oidc

endpoints:
  gateway-url: http://api.umes/
  urls:
    -
      name: krakend-service
      url: /api-docs
      privateurl: .
    -
      name: api1-service
      url: /swagger-ui/api-docs/api1-service
      privateurl: http://api1:8080/api-docs/
    -
      name: api2-service
      url: /swagger-ui/api-docs/api2-service
      privateurl: http://api2:8080/api-docs/
