server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS512
          jwk-set-uri: https://8518-31-222-83-252.ngrok.io/cas/oidc/jwks
