spring:
  security:
    oauth2:
      client:
        registration:
          casum:
            client-id: clientid
            client-secret: thisisnotused
        provider:
          casum:
            issuer-uri: https://6a25-31-222-83-252.ngrok.io/cas/oidc

server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

remote:
  resource:
    baseurl: "http://apigateway:8080/resources"
    #direct call (fails composed response)
    #baseurl: "http://api1:8080/resources"