spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: clientid
            client-secret: clientsecret
        provider:
          okta:
            issuer-uri: http://kubernetes.docker.internal:8001/cas/oidc

server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
