spring:
  security:
    oauth2:
      # client:
      #   registration:
      #     casum:
      #       authorization-grant-type: client_credentials
      #       client-id: clientId0
      #       client-secret: clientSecret
      #   provider:
      #     casum:
      #       token-uri: http://kubernetes.docker.internal:8001/cas/oauth2.0/accessToken
      #       issuer-uri: http://kubernetes.docker.internal:8001/cas/oidc
      resourceserver:
        jwt:
          issuer-uri: http://kubernetes.docker.internal:8001/cas/oidc

server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

logging:
  level:
    org:
      springframework:
        security: DEBUG

remote:
  resource:
    url: "http://resource2:8080/resources/something"