spring:
  security:
    oauth2:
      client:
        registration:
          casum:
            client-id: clientid
            client-secret: ----
        provider:
          casum:
            issuer-uri: http://kubernetes.docker.internal:8001/cas/oidc

server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

remote:
  resource:
    baseurl: "http://resource:8080/resources"