server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          casum:
            client-id: clientId0
            client-secret: clientSecret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          casum:
            issuer-uri: https://0090-31-222-83-252.ngrok.io/cas/oidc
            token-uri: https://0090-31-222-83-252.ngrok.io/cas/oauth2.0/token
      resourceserver:
        jwt:
          jws-algorithm: RS512
          jwk-set-uri: http://entrada:8080/cas/oidc/jwks
