spring:
  security:
    oauth2:
      client:
        registration:
          casum:
            client-id: clientid
            client-secret: thisisnotused
        provider:
          casum:
            issuer-uri: https://3c03-31-222-83-252.ngrok.io/cas/oidc

server:
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

apigateway:
  url: "http://apigateway:8080"
