version: "3"
services:
  sso:
    build: ./cas-oauth
    image: apereo/cas-oauth
    ports:
      - 8001:8080
    volumes:
      - ./cas.properties:/etc/cas/config/cas.properties
    healthcheck:
      test: ["CMD-SHELL", "grep  -rnw '/tmp/logs/' -e 'Ready to process requests'"]
      interval: 5s
      timeout: 5s
      retries: 60

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - login
      - resource
    ports:
      - "80:80"

  gateway:
    image: devopsfaith/krakend:1.4.1
    volumes:
      - ./krakend-gw.json:/etc/krakend/krakend.json
    depends_on:
      - resource

  front:
    build: ./oidc-vuejs
    image: vuejs/oidc
    depends_on:
      sso:
        condition: service_healthy

  login:
    build: ./oidc-login
    image: springboot/oidc-login
    volumes:
      - ./application_login.yml:/app/config/application.yml
    depends_on:
      sso:
        condition: service_healthy

  resource:
    build: ./oidc-resource
    image: springboot/oidc-resource
    volumes:
      - ./application_resource.yml:/app/config/application.yml
    depends_on:
      sso:
        condition: service_healthy
