version: "3"
services:
  sso:
    build: ./cas-oauth
    image: apereo/cas-oauth
    ports:
      - 8001:8080
    volumes:
      - ./cas.properties:/etc/cas/config/cas.properties

  gateway:
    image: devopsfaith/krakend:1.4.1
    ports:
      - 80:8080
    volumes:
      - ./krakend-oauth.json:/etc/krakend/krakend.json

  client:
    image: registry.gitlab.com/guenoledc-perso/idp-oidc-tester:latest
    ports:
      - 8080:80
    volumes:
      - ./.idp-conf:/data/.idp-conf
